# Generated by Django 4.1.4 on 2022-12-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='email_working',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_personal',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_working',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
